language: cpp
compiler: gcc

install:
  - sudo apt-add-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8 libgl1-mesa-dev libsdl2-dev
  - git clone https://github.com/bkaradzic/bx ../bx
  - git clone https://github.com/bkaradzic/bgfx.git ../bgfx
  - git clone https://github.com/premake/premake-core.git ../premake-core
  - cd ../premake-core
  - git submodule init
  - git submodule update
  - make -f Bootstrap.mak linux
  - chmod +x bin/release/premake5 
  - cd $TRAVIS_BUILD_DIR
  - ../premake-core/bin/release/premake5 shaders
  - ../premake-core/bin/release/premake5 gmake
  - cd build

script:
  make config=release_x86_64
  
notifications:
  email: false
